PROGS = arg_parse sys_open sys_read sys_read_error sys_write sys_write_error sys_stdio_1 sys_stdio_2 sys_stdout sys_stderr sys_close sys_pipe bad_addr_1 mm_mmap mm_mmap_error_protection mm_mmap_error_protection_exec mm_munmap mm_munmap_error bad_code_write sys_seek sys_seek_error sys_tell sys_tell_error thread_create thread_join_err thread_join_chain thread_join_complex thread_mm_shared mm_exit_cleanup
DEFINES = -D THREADING
include ../../../kelibc/Makefile
